services:
    db:
        image: postgres:15-alpine
        container_name: medicine_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: medicine_store
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - medicine_net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d medicine_store"]
            interval: 5s
            timeout: 5s
            retries: 5

    # backend:
    #     build: ./backend
    #     container_name: medicine_backend
    #     restart: always
    #     ports:
    #         - "8000:8000"
    #     environment:
    #         DATABASE_URL: postgres://admin:password@db:5432/medicine_store
    #         RUST_LOG: debug
    #     depends_on:
    #         db:
    #             condition: service_healthy
    #     networks:
    #         - medicine_net

    # frontend:
    #     build:
    #         context: ./frontend
    #         args:
    #             NEXT_PUBLIC_API_URL: http://localhost:8000/api
    #     environment:
    #         INTERNAL_API_URL: http://backend:8000/api
    #     container_name: medicine_frontend
    #     restart: always
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - backend
    #     networks:
    #         - medicine_net

volumes:
    postgres_data:

networks:
    medicine_net:
        driver: bridge
